# Generated by Django 3.1.6 on 2021-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.IntegerField(),
        ),
    ]
