# Generated by Django 3.1.6 on 2021-02-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210216_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='lang',
            new_name='languages',
        ),
    ]
