# Generated by Django 3.1.6 on 2021-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210217_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=1, null=1, upload_to='upload/'),
            preserve_default=1,
        ),
    ]
